# Site settings
include: ["_includes"]

title: Trevs drivel
email: trevinkenneth@gmail.com
description: >-
  Super cool thoughts of me

collections:
  posts:
    output: true

theme: jekyll-theme-minimal
markdown: kramdown

highlighter: rouge
syntax_highlighter_opts:
  css_class: 'highlight'

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

skinny_header: true
dark_theme: true
